project_id = "ekzaaptxfwixgmbrooqr"

[functions.ai-style-analysis]
verify_jwt = true

[functions.ebay-integration]
verify_jwt = true

[functions.ebay-oauth]
verify_jwt = false

[functions.subscription-management]
verify_jwt = true

[functions.posting-queue]
verify_jwt = false